name: happy_customer_bank
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.0
  - pandas=2.1.2
  - joblib=1.3.2
  - scikit-learn=1.3.2
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - imbalanced-learn=0.11.0
  - ipykernel=6.26.0
  - jinja2=3.1.2